### ISSUE TITLE
Shuffle button in now playing screen

### ISSUE THREAD

**Issue by rishitraii** [vfsfitvnm/ViMusic#130]
### Feature description

There is only repeat button right now. Shuffle is important while playing songs or else you'll get tired of listening same songs after your favourite song. We do have shuffle play as a whole but we need it after we choose our one particular song. 

### Why do you want this feature?

All music player has it as it's one of the most crucial thing. Vi music is missing it. Thats the only thing, besides its perfect. Perfect ui and functionality. Kudos team 🤍

**Comment by vfsfitvnm** [comment]
The shuffle button was indeed present at the beginning, however I removed it because ExoPlayer, like any other google library, is over engineered and, other than doing its job perfectly, it also makes simple things complicated.

However, I could add a "Shuffle queue" menu entry which reorders the queue randomly (but it keeps the currently playing song). E.g.:

```
"A", "B", "C", "D"
           ^ playing
```
Becomes:
```
"C", "B", "D", "A"
 ^ the playing song always become the first
```
And it would be added here:
<img src="https://user-images.githubusercontent.com/46219656/180661620-3b4f5cc2-266e-48a6-bc2e-309d5305da39.png" width="30%"/>

**Comment by rishitraii** [comment]
Yes. That would be perfect! I too personally don't think it would look clean in the now playing screen. It would be nice if you add it somewhere else. It's a function that is needed.

**Comment by vfsfitvnm** [comment]
I realized this is the place where it fits the most :)

https://user-images.githubusercontent.com/46219656/180745996-03651aae-550b-4c4f-bdfc-8cd56083c816.mp4

**Comment by rishitraii** [comment]
Thanks for listening:)
