### ISSUE TITLE
Consumes a lot of Data

### ISSUE THREAD

**Issue by ghost** [vfsfitvnm/ViMusic#1317]
### Steps to reproduce the bug

Data Consumption is too high. 

### Expected behavior

Should consume less data. 

### Actual behavior

Although it is a great music streaming application, it consumes a lot of data, for example i used it for almost 1 hour straight it consumed around 400mb of data.
Every song takes almost 10 to 15mb which is a lot. 

### ViMusic version

0.5.4

### Android version

Android 9

**Comment by n-ce** [comment]
As a longtime vimusic user, I don't think it's designed in a way to use less bandwidth but instead ease of use is prioritised. As such this is not really a bug but a 'by design' thing. If bandwidth is a constraint for you, I would recommend you to seek alternatives such as [**InnerTune**](https://github.com/z-huang/InnerTune) (which has low bandwidth option) or [**ytify**](https://github.com/n-ce/ytify/) (which is designed for low bandwidth).
