### ISSUE TITLE
Minor progress bar related bug

### ISSUE THREAD

**Issue by luimu64** [vfsfitvnm/ViMusic#148]
### Steps to reproduce the bug

1. Start playing any song in fullscreen
2. Swipe up from any point of the progress bar

### Expected behavior

Swipe is ignored or song gets skipped to the point where the swipe originated from.

### Actual behavior

Progress bar gets skipped to the place where the swipe originated from but the song keeps playing without skipping. In this bugged state the progress won't update until you change song or it ends.

### ViMusic version

0.3.0

### Android version

12 (Crdroid 8.2)

### Additional information

Only minor visual bug, easy to avoid and easy to fix, low priority.

**Comment by vfsfitvnm** [comment]
Yup, I know this bug existed but... ehm... I hoped it could pass unnoticed:tm:.

The bug occurs [here](https://github.com/vfsfitvnm/ViMusic/blob/193c98e20e54b6e4dea01423f3944ad9887c8a29/app/src/main/kotlin/it/vfsfitvnm/vimusic/ui/components/SeekBar.kt#L85).

I start the drag when a press is detected, and I _should_ end it if a vertical drag occurs. However, I'm not sure how to do so - it probably requires writing some custom logic.

**Comment by vfsfitvnm** [comment]
Nah, the fix was easy, indeed.

However, when dragging downwards, the old behavior is better...

Comparisons:

| | Old | New |
| --------------- | --------------- | --------------- |
| Upward drag | <video src="https://user-images.githubusercontent.com/46219656/181905118-71a2f990-3e0e-4d1d-a8b6-72dcea38d566.mp4" /> | <video src="https://user-images.githubusercontent.com/46219656/181905116-91bae25f-8f54-4120-9e52-1ed27cfeab89.mp4" /> |
| Downward drag | <video src="https://user-images.githubusercontent.com/46219656/181905117-0d206b82-6976-464a-9565-a1fccbaad37c.mp4" /> | <video src="https://user-images.githubusercontent.com/46219656/181905209-9cf67c49-2635-433b-a8b2-c0c5cc239c20.mp4"/> |

**Comment by luimu64** [comment]
I think the new behavior is better by being more consistent overall. Also you can clearly see the incorrect skipping still happening while swiping down on the old even tho it gets reset when you maximize the player back up.

**Comment by vfsfitvnm** [comment]
I don't know honestly. If one tries to drag down the player, it may seek the song instead - this is by far more frustrating than just having a "broken" seekbar.
The required logic to correctly address this problem outsources the problem itself...
