### ISSUE TITLE
Music Player screen background based on dominant color in album poster

### ISSUE THREAD

**Issue by John189903** [vfsfitvnm/ViMusic#159]
### Feature description

Right now, Music Player screen background is based on theme, can you use Google palette API to get the background color for Music Player screen.
You can see this behaviour in notification music player. Same feature is avaiable in YoutubeMusic

### Why do you want this feature?

Enhancement

**Comment by John189903** [comment]
@vfsfitvnm , can you please take a look if this feature can be implemented

**Comment by vfsfitvnm** [comment]
https://user-images.githubusercontent.com/46219656/183309392-138350bf-9200-4af5-879a-6e4154c810b9.mp4

**Comment by Malopieds** [comment]
I have to say, looks better than mine ! The colors are better, i had issues with songs like loosing my religion from R.E.M because of the yellow color, can't way to see yours !
Nice choice of music tho

**Comment by vfsfitvnm** [comment]
I'm leaning to apply the colors the whole app.

It looks pretty good with the light theme:

https://user-images.githubusercontent.com/46219656/183511982-071edb60-8ea2-45d3-b588-327fca139a6c.mp4


However the dark theme produces ugly colors when the base is yellow/light green:
<img src="https://user-images.githubusercontent.com/46219656/183512621-d935fce2-8aff-4b83-a14a-7ef22df362a7.png" width="30%"/>

But the major issue with the dark theme is [some background colors appear lighter than others](https://wildbit.com/blog/accessible-palette-stop-using-hsl-for-color-systems), and it looks very bad. I still have to think to a solution.


> I had some trouble (when the song is changing it's not actualised)

That's because you are not writing compose code :P (i.e. `remember`, `mutableStateOf`...)

**Comment by Malopieds** [comment]
>  I'm leaning towards applying the colors to the whole app.
> 
I was asking myself if this would looks good and thought it was top much hut your version looks very good !

> That's because you are not writing compose code :P (i.e. `remember`, `mutableStateOf`...)
> 

Oh okay I see thanks x) that's actually the first time i really fork a project, and almost first time writing kotlin code (and therefore compose) but i do like it a lot !

**Comment by John189903** [comment]
Music player background colors looks great @vfsfitvnm !!

**Comment by John189903** [comment]
@vfsfitvnm , just a suggestion can we the color of notification strip contains time and battery percentage.
Lets say due to some song is background color is getting set as red. Having a black or white background strip on top doesn't look good

**Comment by vfsfitvnm** [comment]
@John189903 Yeah don't worry
