### ISSUE TITLE
Small tweak on now playing screen

### ISSUE THREAD

**Issue by rishitraii** [vfsfitvnm/ViMusic#183]
### Feature description

The "play/pause" of the previous version which was in black accent looked dominant yet minimal. Can you replace the present bluish button with the old black button. Check it yourself once. If its nice do update accordingly. (And when we pause, the circle gets squicircle. Just circle would look good in my opinion)
Btw love the app. Replaced my Spotify and YouTube music completely. Great work devs!

### Why do you want this feature?

Mentioned above 

### Additional information

![PXL_20220704_164742317~2](https://user-images.githubusercontent.com/109918393/183428516-6780b6b8-ed0a-434f-8de8-329f970afd47.jpg)
This ui was really really great already.

**Comment by vfsfitvnm** [comment]
I'll admit, that blue-ish color doesn't look good in the light theme.

However, I'm implementing #159; this is how that song will look like (in light theme):

<p align="center">
<img src="https://user-images.githubusercontent.com/46219656/183432740-dbf7034d-9fe0-4bee-8d94-160cad34f799.jpg" width="40%"/>
<img src="https://user-images.githubusercontent.com/46219656/183432744-19832139-4131-451b-9b73-088ec604d663.jpg" width="40%"/>
</p>

The old black button takes too much importance. But let's see what other people think

**Comment by rishitraii** [comment]
Can you make the pause button circle like the play button.
Out of topic but if the one you sent is the new ui that's being implemented, its not good. The design is going backwards, as per me (no hate, just a feedback). The old ui was perfectly fine. Wasn't it? But yes its not just me. The others want different i see. I'm the most concerned with the visual perspective. I look for apps with beautiful designs and then i found this gem. It'll be sad for me to see it going backwards in design. Also the accent color thing is something that I won't support because they won't look aesthetically appealing (unless you make it an option to choose, and not compulsory)

**Comment by vfsfitvnm** [comment]
<p align="center">
<img src="https://user-images.githubusercontent.com/46219656/171632003-33a017d7-cdc8-4588-a1fc-45be294969a8.png" width="30%"/>
<img src="https://user-images.githubusercontent.com/46219656/183442115-f4fb3b67-3ff0-43f3-a8cf-eddbdd5c16d8.png" width="30%"/>
</p>

Nah dude - there's no way the old one is better than the current one. The old UI is certainly fine, but you just can't say the new one is not. If so, what are the reasons? How it is going backwards? For just a button color?

**Comment by rishitraii** [comment]
![183432740-dbf7034d-9fe0-4bee-8d94-160cad34f799](https://user-images.githubusercontent.com/109918393/183445865-8b0f694c-028c-42e6-94d4-a03fc6f250ef.jpg)
This picture that you sent looks different, is it because its cropped? That looked odd. I said it because of that, not button color. Anyway, i do feel like I'm wrong. I apologise. 
But do make rounded pause button, if you can.

**Comment by vfsfitvnm** [comment]
Well, if you are referring to the picture size, that's because of my device aspect ratio lol. For reference, this is how it looks in a taller device:

<img src="https://user-images.githubusercontent.com/46219656/183448854-3103cf31-70ec-4142-8319-956b37353ef7.png" width="40%"/>

Also, I won't change the button shape: I like having its shape switching between a circle (when playing) and a rounded corner square (when paused).

**Comment by vfsfitvnm** [comment]
Feel free to share your ideas or opinions whenever a new feature request pops up (i.e. "_I like it why..._", "_I don'l like it why..._", "_I don' care_"). It really helps me taking decisions

**Comment by deepu2** [comment]
The play button with matching color looks gorgeous compared to the darker one.

**Comment by yant0** [comment]
Unrelated opinion from the issue but,

> Also, I won't change the button shape: I like having its shape switching between a circle (when playing) and a rounded corner square (when paused). It is a simple but quite powerful animation.

I would like to disagree on the animation for pause and contionue to have "powerful" animation. I personally think its really sluggish and seems out of place. Not that the animation it self is the problem, but the speed of the animation. I say so because the current button have a 1 second delay before actually doing the animation. It gives me the impression of older version of android which you need to wait for it to do something after clicking.

I think that the buttom should be morphed to the other shape immediately after pressing the button

**Comment by vfsfitvnm** [comment]
Not sure what you are referring to:
https://user-images.githubusercontent.com/46219656/183601623-8e72245b-89a1-4e6b-ba82-3ffb26b999f2.mp4

Also, the playback starts/stops immediately - before the animation finishes :thinking:

**Comment by yant0** [comment]
Hmm is it just my device? I get animation delay whenever i pres start/stop button.

https://user-images.githubusercontent.com/80298071/183663926-6befe784-33e5-4cda-ba70-03b3b49c638a.mp4

Im using android 11 with 3 gigs of ram and i believe sd 600 using 3.0 / latest

**Comment by vfsfitvnm** [comment]
You may have set an animation scale/delay through your system settings

https://mobileinternist.com/wp-content/uploads/2019/10/animation-scales-android.jpg

**Comment by yant0** [comment]
hmm as far as remember i never tampered with animation speed on my phone. I checked them and its 1x. I try setting them to 0 and the animation still laggs. I used a custom rom that might be it?

Idk if this is an actual bug since i dont own a stock oem rom so i dont feel obligated to create a new issue. Anywho, if its working great for others i take back what i said.

**Comment by vfsfitvnm** [comment]
I don't think there is a bug here - and I'm really struggling at finding in your video the delay you are talking about. I mean, the shape morphs when the button is released, not when it's just pressed (because it follows the player state: the player won't play/pause until you release the finger). Maybe you expect the shape to change when just pressed? Would you show me what the expected behaviour would be?

**Comment by yant0** [comment]
Its like the matter of easing (of animation time) i suspect. I feel mine is like ease in and out so when i tap it doesnt go transform immidiately.

**Comment by vfsfitvnm** [comment]
The default animation is spring based, so easing can't be controlled - I'll see if a `tween` of 200ms + `LinearEasing` produces a smoother change
