### ISSUE TITLE
Vimusic discord server 

### ISSUE THREAD

**Issue by owencz1998** [vfsfitvnm/ViMusic#209]
### Feature description

I'd like to make a vimusic doscord server that will have github webhook integrated and more would you be interested.

### Why do you want this feature?

Would like to help out not sure where I should of put this sorry if its a problem :)

**Comment by Jak2k** [comment]
👎

**Comment by vfsfitvnm** [comment]
The slow pace of github makes it so that the user has to think better about what it wants, why it wants it, and whether it's possible or not.

I already have to deal with low effort (and duplicate) requests here, I can't even imagine what would happen in a discord server.
I don't want to give technical advices or answer to stupid questions. I don't have enough patience and I'm not paid for it. This might be a bit rude of me, but it's the truth.

I recognize direct communication allows for a more natural conversation, but most often it results in a big waste of time.

**Comment by owencz1998** [comment]
No worries
