### ISSUE TITLE
Make hiding songs more convenient

### ISSUE THREAD

**Issue by SebiderSushi** [vfsfitvnm/ViMusic#225]
### Feature description

Add the "Hide" feature in more places and make it more accesible.
Remove hidden songs from the playing queue to avoid listening to them again after the queue loops around.

### Why do you want this feature?

There is currently no local search feature and even with an internet connection it is not possible to "Hide" any songs from the search results screen.
It's very cumbersome to scroll through the whole list of songs in order to find and remove one of them.

Usually i decide whether i want to remove a song when listening to it or right afterwards. Therefore, the most convenient places to have the "Hide" function in the context menu would be the "Now playing" screen and the playing queue.

When i decide to Hide a song i do this because i don't want to listen to it again. I immediately remove it from the playing queue as well to make sure it won't be cached and played again on accident.

**Comment by vfsfitvnm** [comment]
(part 2)

Well, I could easily add the "Hide" button to every menu - but I won't do it as it doesn't make a lot of sense. The "Hide" feature does two things:
- Deletes the cache of that song
- Reset the playback time, so it won't appear in the home screen

And yes, it can be used to remove songs you don't like.

> Usually i decide whether i want to remove a song when listening to it or right afterwards. Therefore, the most convenient places to have the "Hide" function in the context menu would be the "Now playing" screen and the playing queue.

This is true. The reason why I didn't add that button in the now playing screen is due to the nature of the "Hide" button. In fact, it doesn't delete the song from the database - so, when such song is skipped, its playback time gets increased again and so it will appear again in the home screen. Of course I can easily implement something to avoid this, but then I would feel forced to handle every other edge case (e.g. removing that song from the queue and preventing it to appear again) - thing I don't want to do.

However, you usually skip a song when you aren't enjoying it, so you only listen to it for a little period of time. In such case, I could add an entry (in Settings > Cache) that hides every song you listened to for e.g. less than two minutes.
Alternatively, #161 covers this case I guess.

**Comment by SebiderSushi** [comment]
Understandable. Thanks a lot for the quick & direct response.
