### ISSUE TITLE
Remove "loop none" option

### ISSUE THREAD

**Issue by vfsfitvnm** [vfsfitvnm/ViMusic#276]
Currently, the playback has 3 loop options:

1. **Loop none**: when the queue ends, the playback ends as well
2. **Loop all**: when the queue ends, the playback re-starts from the first song in the queue
3. **Loop one**: when the playing song ends, it is restarted

However, I think the "loop none" is useless: in which scenario its behavior is desiderable?
Personally, I always make sure it's not selected, because I'd rather listen to the same songs than having silence.

Preview:

https://user-images.githubusercontent.com/46219656/188190769-06630fb1-e258-43a2-a0d9-aee8ec1afa6d.mp4

What do you think?

**Comment by vfsfitvnm** [comment]
The sleep timer is already present :smile: 

<img src="https://user-images.githubusercontent.com/46219656/188282352-2cf7c1d1-45a4-4373-b3a1-632563633b5a.png" width="25%"/>

**Comment by vfsfitvnm** [comment]
Regarding the icon, this is the alternative:

https://user-images.githubusercontent.com/46219656/188282467-cf62d3e5-2af3-40aa-9b39-25825086128a.mp4

**Comment by Jak2k** [comment]
Can you add a "Play until end of Playlist" option to the sleep-timer, because I use "loop none" quite often.

**Comment by Jak2k** [comment]
If I hear a playlist and then want to hear sth. other. When I would append the other playlist, Shuffle would shuffle everything, jot just the second playlist.

**Comment by vfsfitvnm** [comment]
I don't get how the "loop none" would help here?

**Comment by Jak2k** [comment]
With the option I notive when the playlist is heared.

**Comment by vfsfitvnm** [comment]
You can simply enqueue the playlist you plan to listen next, so you don't have to worry about it at all (even if the "loop none" option was still present) :smile:

**Comment by Jak2k** [comment]
But when I click on shuffle, the old and the new playlist will be mixed

**Comment by thornySoap** [comment]
> @Jak2k In which situations do you use the loop none?

I personally would use (and have used) "loop none" most of the time.
Sometimes I just want to hear one song to motivate myself e.g. for starting to clean teeth. With "loop none", playback would stop after the song ends, but I could finish cleaning teeth and meanwhile think about the song. But now the problem is that the song will repeat, so I don't have this short, but nice silent moment afterwards anymore.
Also, songs often have different moods at the beginning and at the end. So when I want to hear one only once, I have to stop playback really quickly after it has ended. Otherwise only the first 2 seconds of the repeated song could through me out of the "end mood" which is really annoying.

**Comment by nR3D** [comment]
I agree with @thornySoap, sometimes you just want to listen to a single song/album/playlist. All music players that I know of have 'loop none' set by default, and "I don't use it so neither do you" is probably not the best excuse for removing a feature like that.
Likely 45235ac won't take any work to rollback.

**Comment by thornySoap** [comment]
Just now it happened again. Please don't ask why, but I just heard the complete soundtrack of a Star Wars film. The music of the credits ended, I was hanging around in memories. But then suddenly the opening fanfare bloated the mood completely away, because I was not fast enough to stop it. That is very annoying

**Comment by vfsfitvnm** [comment]
My point was it's very annoying to cycle through three loop options: I proposed to remove the one I thought was used the least, nobody complained so I proceeded. **All I care is the ability to set and unset the "loop one" option with only one tap** - and I can already tell you the three loop option cycle won't come back.

However, I understand your points. I see two solutions:

1) Remove the "loop all" option instead (yet it would cause similar complains)
2) Long press to set the "loop none" option (it would be hard to discover?)

**Comment by vfsfitvnm** [comment]
Of course there's a third option, that is adding an option to disable the automatic queue looping. But, to do so, I must understand how much frequently a user changes the loop mode from "loop all" and "loop none". Is that a user preference, or does it depends on the playlist?

**Comment by nR3D** [comment]
> 1. Remove the "loop all" option instead (yet it would cause similar complains)
> 2. Long press to set the "loop none" option (it would be hard to discover?)

1. Yeah, as I previously said those three loop options are offered by all music players, so removing one of them will eventually lead to more complains
2. It could work, maybe a double tap (to disable looping sort to say) might be easier to discover since it's what people are already doing to cycle between the options. But again, the way it was previously is how new users will expect it to work, so be ready to hear that question a lot.

> Is that a user preference, or does it depends on the playlist?

Personally, I use 'loop none' 90% of the time, but I don't like the idea of digging through the settings for that 10%

**Comment by thornySoap** [comment]
![image2](https://user-images.githubusercontent.com/115401023/196126411-01890f72-d469-4006-9967-3a8b85ee57f3.png)
Maybe put the loop all/none option here?

**Comment by vfsfitvnm** [comment]
That's a good placement (the "loop all/none" involves the whole queue rather than a single song), however I'm not sure about the icon (even though a simple text would be fine as well) and what should happen when the "loop one" option is enabled as well. What loop mode has the highest importance? Does swapping the queue loop mode also reset the single track loop?

**Comment by nR3D** [comment]
@vfsfitvnm 
Will the selection be kept in memory?

**Comment by vfsfitvnm** [comment]
Of course, it will stored persistenly

**Comment by thornySoap** [comment]
I like it really much too. But couldn't "loop none" be missunderstood since a single song _would_ loop if "loop one" is checked? Maybe "don't loop" would be more concise

**Comment by vfsfitvnm** [comment]
Hmm, I could either disable that button when "loop one" in enabled (the user has to unset the "loop one" first, but this is a thing he would have done anyway to make the "loop all/none" option take effect) or find another name. "Don't loop" refers to an action rather than a state, so it may be confusing, either "loop disabled"/"loop enabled" or "queue loop off"/"queue loop on" sounds better

**Comment by vfsfitvnm** [comment]
Implemented. I opted for the "queue loop off"/"queue loop on" thing as temporary (?) solution

**Comment by dialex91** [comment]
this is the worst idea you ever had

**Comment by thornySoap** [comment]
> this is the worst idea you ever had

You haven't really read the thread, have you?

**Comment by ARBoyGo** [comment]
> Implemented. I opted for the "queue loop off"/"queue loop on" thing as temporary (?) solution

Honestly, We are loving it. Like sleep timer is there, Still I don't need it, Cause I don't know when I'll sleep, And whenever I predict my time, And They stop in middle, (Like I keep my phone far from my hand reach, I use headsets.) So Loop none AKA Queue loop off is just great. Maybe it's about personal preferences.

**Comment by dialex91** [comment]
> You haven't really read the thread, have you?

If I hadn't read it, I wouldn't have said it.
