### ISSUE TITLE
Delete song from history should not remove it from playlists

### ISSUE THREAD

**Issue by max5354** [vfsfitvnm/ViMusic#29]
### Steps to reproduce the bug

if i press "remove" button in history than it delete that song from playlist too. We just want to remove that particular song from only history not from playlist. So please improve that.

### Expected behavior

Not to remove/delete that song from playlist.

### Actual behavior

It delete also song from playlist if we press "remove" button.

### ViMusic version

0.1.3

### Android version

Android 10

**Comment by vfsfitvnm** [comment]
When you press the "Delete" entry, it clearly states the song will be removed from any playlists as well - this happens because the song gets deleted from the database. This is a design decision I won't change.

History/Most played/Favorites are indeed not real playlists, but collections. The History collection displays every song you listened to for at least a minute - that's all.

Why do you want to hide a song from that list? What are the advantages?
