### ISSUE TITLE
Option to add entire albums (every single track assigned to it) to a custom playlist

### ISSUE THREAD

**Issue by ElizabethWega** [vfsfitvnm/ViMusic#303]
### Feature description

Hello!
I can't access my phone sometimes, so constantly switching from an album to album, just to hear other songs, can be tiring. I've added several albums from different artists as standalone playlists, but just as I've said before, I have to jump to and fro to hear another track from different/same artist. I've tried pressing several buttons but found none that could help me. Enqueuing every single album every time I open the app consumes a wast amount of time. Being able to add a whole album (every single track that it consists of) to a custom playlist of mine would be great. Is this possible? Anyway, thank you for your time.
Cheers!

### Why do you want this feature?

I do believe this would be a helpful QoL feature, saving time in some cases and also practical.

**Comment by vfsfitvnm** [comment]
Hmm, such feature is a edge case so I won't add it. However, I think #161 will help you for sure.
The "persistent queue" setting _may_ help you as well (it depends on your use case) because you don't have to recreate the queue every time you open the app anymore, so you can enqueue albums only once.
