### ISSUE TITLE
Move menu bar to the top/bottom

### ISSUE THREAD

**Issue by Fatcakes** [vfsfitvnm/ViMusic#390]
Feature description
The side is a bold choice. Anyway we can get an option to put it at the top or bottom that hides when you scroll down? Either that or a way for the side menu to slide out and stay hidden most of the time? Maybe use icons instead of plain text also to make the app look more polished?  Sorry if there is already another open instance of this request.

Why do you want this feature?
The side menu being there all the time really destroys the aestetics of the app. A top would be better that hides when scrolling would be better. I honestly even prefer the previous look on the search page on the previous release to the side menu.

**Comment by haernerdy** [comment]
Support!

**Comment by haernerdy** [comment]
Supported!

**Comment by Elim707** [comment]
> Feature description
> The side is a bold choice. Anyway we can get an option to put it at the top that hides when you scroll down? Either that or a way for the side menu to slide out and stay hidden most of the time? Maybe use icons instead of plain text also to make the app look more polished?  Sorry if there is already another open instance of this request.
> 
> Why do you want this feature?
> The side menu being there all the time really destroys the aestetics of the app. A top would be better that hides when scrolling would be better. I honestly even prefer the previous look on the search page on the previous release to the side menu. 
> 

What if they put menu bar at bottom??

**Comment by Fatcakes** [comment]
@Elim707 that's a possibility,  but I feel like it would be better at the top and it autohides when scrolling. Having it there taking up screen real estate isn't ideal.

**Comment by Elim707** [comment]
> @Elim707 that's a possibility,  but I feel like it would be better at the top and it autohides when scrolling. Having it there taking up screen real estate isn't ideal.

Ohkay cool!!

**Comment by Pentaphon** [comment]
> The side menu being there all the time really destroys the aestetics of the app. A top would be better that hides when scrolling would be better. I honestly even prefer the previous look on the search page on the previous release to the side menu.

I really don't like the side menu either. It gives the app more of a learning curve and it really confuses older people that I show to the app to for their music listening needs. When I gave the app to an older person they kept turning their phone to the side to read the menu and they thought it was kind of weird to have the text in a "cris-cross" as they called it. 

I think a bottom menu would work the best for this app. It makes things much simpler, especially for new and older users.

**Comment by arfanmrafeek** [comment]
> `I really don't like the side menu either. It gives the app more of a learning curve and it really confuses older people that`
I do agree with this, New UI is very hard for old people and someone who is new to using mobile phone. I had to setup this app on many phones by now. I didn't give them update because it's quite hard for them to understand, I hope it's great to give an option to change menu bar UI. 
I was actually a fan of old UI, Though I changed my mind, It's okay. But would be good if we have an option.

**Comment by Pentaphon** [comment]
> It's better if we have option, Like there are fans for both UI.

Yeah but I think a bottom menu UI would be the best for most people since it is the easiest to read.

**Comment by Fatcakes** [comment]
@Pentaphon yeah you're probably right about that.

**Comment by Pentaphon** [comment]
@vfsfitvnm you may want to consider making the bottom bar UI the default UI when installing ViMusic because:

1) It follows current Material Design standards
2) It's the most familiar UI to most users
3) Older people may be confused as to how to go to into the settings to change to the bottom bar UI. They usually do not fiddle with settings and simply want to search and play music. I've found that this app is very popular with older people who want to use their phone to play music without having to deal with a music subscription. They are delighted when they find out this app exists.

**Comment by Fatcakes** [comment]
@Pentaphon I think @vfsfitvnm gets it. He didn't immediately close the request after the change so he is probably working on something. I do agree the bottom is where it should go in portrait mode. The landscape mode looks great the way it is honesty.

**Comment by vfsfitvnm** [comment]
I want to thank you all for the participation and interest, but the bar will stay where it already is.

The bar (as it is) can't be positioned at the bottom (explanation [here](https://github.com/vfsfitvnm/ViMusic/issues/172#issuecomment-1261390934) and [here](https://m3.material.io/components/navigation-bar/overview#takeaways)).

The only aspect that needs to be improved is the navigation with one hand (#398); the other non-personal-taste reasons you mentioned just doesn't make sense to me:

1. Old people are not who I think to when I'm working on this app (and, you know, I'm not interested in growing the user base as much as I can);
2. There's no relevant information written vertically so there's nothing "hard to read";
3. "Phones are getting taller, not wider". So what? Phones are just getting taller, they aren't narrowing. They don't look like [this](https://i.imgur.com/zmdHsBp.jpg) yet, do they?

I can see the new layout has been a bold choice, and as such, people may not like it at first because it's not what they are used to. However they will hopefully habituate in a relatively short time span (and maybe like it as well, but this is and will always be a personal preference). If they don't, and they don't care about contributing, they can just use another app: I will not care as well.

The new layout addresses few unavoidable problems of the old layout.
1. **Content growth**: it is now possible to grow the content of a screen as much as I want to (as I can just add a new tab for it) without stacking everything vertically:  quick picks and a _true_ artist page (just to cite two) would have been impossible to implement otherwise.
2. **Content selectiveness**: it is now possible to see only the content you are interested in and you won't pay for what you don't. If you don't care about quick picks, then just don't open that tab (networks requests will not be fired). If you don't care about the other versions of an album, then just don't open that tab (networks requests will not be fired). I could continue.
3. **Visually centered content**: people tend to track the content of the screen through images. The vertical bar at the left makes the thumbnails of the songs closer to the center of the screen, giving a stronger perception of centering and making the songs easier to track and recognize (the eyes move less). The left and right side of the screen are what people look the least, that's why I didn't put relevant or mutable information right there. Personally, after getting used to it, it feels uneasy to look for a song in the queue (where images are still close to the edge).

**However**, changes are just _not programmed_, but not _forbidden_. I already spent enough time into this and my level of satisfaction is high enough I don't want to get frustrated again looking for other solutions. That's why, until I don't change my mind, <ins>a new redesign will be considered only if a complete, truthful and detailed sketch of the whole (redesigned) app is presented to me</ins>.

That said, I won't accept complaints in further new issues about this topic (of course, <ins>solutions</ins> are welcomed).

**Comment by Pentaphon** [comment]
Alright, well since the dev says he won't fix it and doesn't care if we use another app, Music aka Innertune just got a redesign and it's bottom-bar only. It's quite similar to ViMusic so if people really need a more traditional UI, there it is. That should be the end of this discussion. 

https://github.com/z-huang/InnerTune

**Comment by kj** [comment]
Thanks @vfsfitvnm. I personally find it jarring so I'm a bit disappointed, but I appreciate the work you've put into this (none of us are entitled to it) and I'll try to get used to it. It's nice to have clear expectations at least. Good luck!

**Comment by Fatcakes** [comment]
@vfsfitvnm I conceded that you're sticking to the already established design, but is there anyway we can move what's already established around a bit? Most of us are right handed. Can we move the men bar to the right above the search button and have the settings button at the top right of the screen and align the songs to the left side of the screen? I don't know how much work that entails, but I feel like most of us would be satisfied with that.

![](https://ibb.co/JrVVrhr)

**Comment by vfsfitvnm** [comment]
> But may I ask you what's the objective behind not making the main tabs slightly modifiable, as in disabling 1 or 2 of them?

It has a bad effort/usefulness ratio now. I will probably do it sooner or later.

> Can we move the menu bar to the right

I'm right handed too. I tried that setup, and honestly it looked completely unbalanced and disordered. Somehow the bar ends up taking too much visual attention. Probably because we are left-to-right readers

**Comment by Fatcakes** [comment]
@vfsfitvnm damn man...that sucks. I thought maybe you were a lefty. Can you post a screenshot of how it looked for shits and gigs?

**Comment by vfsfitvnm** [comment]
It looked exactly like this
https://github.com/vfsfitvnm/ViMusic/issues/394

**Comment by vfsfitvnm** [comment]
However, another solution I can think of is ditching navigation bars completely.

`SettingsScreen`, `SearchScreen`, `SearchResultsScreen`, `PlaylistScreen`, `AlbumScreen` do not require a navigation bar already.

The problematic screens are `HomeScreen` (which should contain quick picks, artists, albums, etc) and `ArtistScreen`.

`ArtistScreen` could just be condensed to "Overview" (where the info is fetched from the network) and "Library" (where local songs from that artists are displayed). However, not everyone wants to wait for a network request to finish when opening a screen. Maybe I should cache more info than what I already do. That would solve this problem, but would increase the database size noticeably and complicated the codebase (not two deal breakers for me).

However, the `HomeScreen` problems still exists and I'm not sure how I could organize it, but I will certainly come to a solution.

Most importantly, I still believe at point 3 (**Visually centered content**), so the space at the left will most likely remain as I **really** enjoy the overall screen appearance with it.

**Comment by Fatcakes** [comment]
@vfsfitvnm I think that it looks quite in the pic your referencing because the title "quick picks" should be aligned to the left edge, and the search should be aligned to the right side. The seem to be in the middle kinda slightly of and I think that might be what's making it look strange.

That being said you're the boss.  I will stay the bar really does add alot of functionality so I don't know what the answer is.

**Comment by arfanmrafeek** [comment]
@vfsfitvnm 

> However, another solution I can think of is ditching navigation bars completely.

Also ditch status bar. I'm using Redmi Note 10 5G globe version, And I'm using lawnchair 12 beta version, It has an option to hide status bar. I even tried a app which does that. You can check my screenshot in #400 .

**Comment by quazar-omega** [comment]
I think while the new design needs a little getting used to, it does work pretty well.
I just wanted to ask, since the intent seems to freely expand the options, why wouldn't a navigation drawer be used instead? Is it to keep the transition between pages seamless?

**Comment by vfsfitvnm** [comment]
@quazar-omega 
The _modal_ navigation drawer (https://m3.material.io/components/navigation-drawer/) simply can't suit our needs (well, it _may_ fit int the home screen, but not in the other - and yes, that would solve what I said in my [previous comment](https://github.com/vfsfitvnm/ViMusic/issues/390#issuecomment-1281956475)).

I made an attempt to remove the vertical navigation bar yesterday. It's certainly possible...

https://user-images.githubusercontent.com/46219656/196721873-4a3de619-f4af-42fb-b51a-df9181e9af2f.mp4

...but it somehow looks so arid yet there's a lot of content in it. I don't know how I could improve it.

At this point I really think having something at the left side of the screen also contributes in making a better "look & feel"...

**Comment by quazar-omega** [comment]
@vfsfitvnm 
> I made an attempt to remove the vertical navigation bar yesterday. It's certainly possible...

Yeah, removing the navigation altogether would make it definitely too cumbersome to, well, navigate.

> The *modal* navigation drawer simply can't suit our needs

I guess that's true, I was thinking along the lines of moving some of those pages in the drawer and keep a bottom bar with the ones you would most frequently visit, but after thinking more about it, it would be very jarring since those are all at pretty much the same level of importance. Unless the future additions will be of the same kind, then maybe I could see those in a drawer, but tbh I don't have other ideas to fix these problems right now.

I also want to say that the current design is unique in a way that makes the app stand out while remaining functional, so I don't think there's a necessity to change it either, still props for being open to consider other perspectives while you're trying to land on final design.

**Comment by vfsfitvnm** [comment]
I think I got THE idea. It is unusual for a music player, but it's a popular layout people are already used to.
Let's see if the real look matches the one I have pictured in my mind!

**Comment by arfanmrafeek** [comment]
I'm feelin something like Twitter, Reddit, Snapchat, Gmail etc....

**Comment by arfanmrafeek** [comment]
> I'm feelin something like Twitter, Reddit, Snapchat, Gmail etc....

Well if that's the case (Navigation Drawer), You need to check Tablets and TV screens working well with this.
