### ISSUE TITLE
How does "quick picks" work?

### ISSUE THREAD

**Issue by PassionateG1t** [vfsfitvnm/ViMusic#413]
I merely want some clarifications if possible:

What does the star on the first song represent? I'm assuming it's what the rest of the recommendations are based on?

When do recommendations update? At first they used to update after every new song I listen to. Now they rarely update.

Thank you in advance.

**Comment by vfsfitvnm** [comment]
> I'm assuming it's what the rest of the recommendations are based on?

Exactly.

> When do recommendations update?

They are updated when there's a new trending song. The trending song is the song you _recently_ listened to the most. Basically, it sums the **weighted** playtime of each song and then picks the song with highest score. Playtime divided by the number of days since the event (30 minutes -> 15 minutes -> 10 minutes -> 7.5 minutes). The algorithm is pretty basic, but that's all what I came up with.

If the trending song doesn't change, it is likely you listened to that specific song _a lot_ (e.g. an hour) compared to the other ones.

Not sure how that can be improved given the info I have. Maybe I should weight the playtime in such a way that after a day passes, its value is halved (30 minutes -> 15 minutes -> 7.5 minutes -> 3.75 minutes), or maybe divide by the number of "haf-days" (i.e. 12 hours).

**Comment by Fatcakes** [comment]
@vfsfitvnm please add that. It's stuck on Olivia Rodrigo and I don't even know who that is. My recommendations are ass because of it. 🤣

**Comment by vfsfitvnm** [comment]
Yep, previous versions had a bug (an exoplayer bug) which caused the playtime to be incorrectly calculated. Long story short, you can have song you never listened to as trending song, unfortunately. `v0.5.1` does not have this bug anymore.

**Comment by vfsfitvnm** [comment]
@PassionateG1t Do you have further questions?

**Comment by vfsfitvnm** [comment]
_inner peace achieved_

**Comment by NeeRaj-2401** [comment]
> Do you have further questions?

@vfsfitvnm As u mentioned it is based on the trending song..i.e. song we recently listened to most..


So can u make an option to fetch the quick picks Manually
Afterall it is fetched from a song .. so it can be manually entered tooo.. 
> If the trending song doesn't change, it is likely you listened to that specific song _a lot_ (e.g. an hour) compared to the other ones.

in such scenarios .. manual fetch/refresh quick picks will be helpful

**Comment by vfsfitvnm** [comment]
You can already remove the trendng song. If you want to see quick picks for a specific song, #502 is what you are looking for
