### ISSUE TITLE
ViMusic does not appear when trying to share url from browser

### ISSUE THREAD

**Issue by rancidfrog** [vfsfitvnm/ViMusic#433]
When sharing to app from browser,
All other apps show up, except vimusic, 
![](https://i.imgur.com/hPlIF45.png)
Maybe take a look at their code to see how the proper implementation for sharing should be,

- https://github.com/TeamNewPipe/NewPipe
- https://github.com/JunkFood02/Seal 
- https://github.com/z-huang/music

You need intent filter,

https://github.com/z-huang/music/commit/7596a2cac5a248d25fd54fd4e4ecc21bec477662

https://github.com/JunkFood02/Seal/commit/cc356360404ef2f37d41a31bffb3ef02e7347bf1

https://github.com/JunkFood02/Seal/blob/ced2114221fd51451397d00dbb1947f28fe8848e/app/src/main/java/com/junkfood/seal/MainActivity.kt#L73

**Comment by vfsfitvnm** [comment]
What's the link you are trying to share?

**Comment by rancidfrog** [comment]
https://youtu.be/wtKMoLwXOBE

**Comment by vfsfitvnm** [comment]
You have to select "Open with", not share.
<img src="https://user-images.githubusercontent.com/46219656/195844663-8b9f778e-1ad7-4d9b-9fe4-3f1d88f495d1.jpg" width="30%"/>

**Comment by rancidfrog** [comment]
But,
Why?
All other apps work with Share.
Also, not all browsers support or have open with option

**Comment by vfsfitvnm** [comment]
>  So you are forcing users to not use browser to open Url as default.

Did you enable vimusic to open youtube links (go to the system app settings)? If you have Android 12+, you have to do this manually

**Comment by arfanmrafeek** [comment]
> Did you enable vimusic to open youtube links (go to the system app settings)? If you have Android 12+, you have to do this manually

I tried it(All the ways), Not working. it is opening in chrome even cleared the chrome and my app settings preference etc.... Now I think it's only available in Firefox. I installed it. Let me try. Tried seem not working, Though Share button working in all browser, For Newpipe, Libretube and Blackhole. 

I don't know, Anyway, It's irritating in some situations but I use it just like search in ViMusic.

**Comment by vfsfitvnm** [comment]
Chrome is known for not adopting features other browsers have (see https://github.com/vfsfitvnm/ViMusic/issues/62#issuecomment-1171576901).

However, I downloaded it and it can still open vimusic when visiting a link.

All you need to do is:
- Set the other apps (youtube, youtube music) to NOT open the supported links
- Set vimusic to open the supported link
- Clear chrome cache

If you can't do thay, you can still paste the link somewhere else (e.g. telegram) and tap it

**Comment by arfanmrafeek** [comment]
Can you show, A share recording?

**Comment by ARBoyGo** [comment]
https://user-images.githubusercontent.com/69381592/201328427-cbc4fc6f-e411-4983-8d30-3512041ad672.mp4

This is what I'm facing. 
I disabled my YouTube for this to work. XD 🤣

**Comment by ARBoyGo** [comment]
I can not see the option open with.

Any idea how to do it? 
<img src="https://user-images.githubusercontent.com/69381592/201345825-05c23686-7c9c-4448-90cd-cab372aea592.jpg" height="300">

**Comment by SebiderSushi** [comment]
I also find it quite cumbersome to get android to do what i want in this situation.
Additionally, i usually want my device to use a default app for opening links with no extra steps in the way most of the times while still being able to relay the url to another app from time to time as a one-off thing.

Some apps might allow me to choose "Open with..." when opening a link but most don't and this use-case falls apart and turns into lots of back and forth for just piping a link around.

I get that this is isn't the clean method from a programming perspective and not how the `VIEW` and `SEND` intents are intended to be used but here we are. Its a UX mess and navigating it can be weird. But i don't see how exposing ViMusic in the share menu causes a delevopment overhead. It seems like a very obvious choice for its benefits.

From my perspective, the feedback shows that other users expect this as well and other apps also adapt to this expectation and just make things more convenient for users. Even Browsers these days commonly appear in the share menu because otherwise with the mechanisms at hand some situations just get extremely annoying. (Example: Bromite, Fennec)

**Comment by ARBoyGo** [comment]
@vfsfitvnm It was my phone issue, It is clear after doing these steps. 
if any MiUi users need it. share this.
1. Download an app called "Hidden Settings for MIUI" from the play store
2. Click on Manage Applications --> ViMusic --> Open by default
3. Select all the links
