### ISSUE TITLE
Opening, closing, then immediately reopening the settings page closes the app

### ISSUE THREAD

**Issue by mhmdanas** [vfsfitvnm/ViMusic#517]
### Steps to reproduce the bug

1. Open ViMusic
2. Press on the settings button
3. Press the back button to close the settings page
4. Immediately press on the settings button

### Expected behavior

The settings page should open.

### Actual behavior

The app is closed. Note that this is not a crash, and the app stays open in the background after pressing the settings icon. The ADB logs show nothing amiss either (no stacktrack or anything). Maybe the settings button "thinks" it's a back button for a brief moment after the settings page is closed?

### ViMusic version

0.5.2

### Android version

Android 12

### Additional information

The phone is a Galaxy A51.

**Comment by vfsfitvnm** [comment]
I wouldn't call this a bug. This happens because the back button sends "back" events (the same ones sent by system/hardware buttons). During the sceeen transition, that button still captures taps, and if you are fast enough, you can manage to tap it a second time. So, the app receives two back events: the first one leads you to the home screen, the second one makes you leave the app. Kind of expected behavior :)
