### ISSUE TITLE
Prevent accidental queue loss

### ISSUE THREAD

**Issue by selurvedu** [vfsfitvnm/ViMusic#541]
### Feature description

After tapping a random song by accident, you lose your whole queue as it gets replaced with a new one.

I see several ways to prevent losing a queue:

1. A snackbar or a similar UI element with an undo action.
2. A screen where you could review and play your previous queue(s).
3. A modal dialogue box asking if you really want to replace the active queue with a new one.

Option # 1 is the easiest to implement, no other UI changes are needed, and it's a small element that won't add any clutter IMHO. I don't know a lot about building Android UIs, so another element may suit this purpose better.

Option # 2 is the most preferable one IMHO. It could even be combined with option # 1. Having N queues saved would let you switch between them and they could be used like "transient playlists".

Option # 3 is the worst one IMHO. NewPipe does that, but it can be disabled in the settings, and I honestly don't remember whether it's even enabled by default. I consider this option as the worst one because in NewPipe that dialogue box is often very annoying, however, sometimes it really saves the day if you inadvertently tapped the wrong thing.

### Why do you want this feature?

I really liked ViMusic on my first usage session and spent a whole hour on tapping here and there, diligently picking songs, editing the queue etc., only to lose my shiny new hand-picked list with a single wrong tap. Then this happened a few more times, but with much shorter queues and much less time wasted.

I discovered the lack of #539, #540, #161 and, most importantly, #374 on that session as all of these are related to my desired workflow.

I also want this (i.e. option # 2) to be able to see what songs were suggested in old queue(s) that are not being suggested in the current / future queues – i.e. I remember there were some cool songs on that queue I lost / replaced, but I don't remember which ones they were, so I can't add them back.

**Comment by ARBoyGo** [comment]
Bro you typed this issue like hell 😂

**Comment by selurvedu** [comment]
So not even a snackbar? That's a pity.

**Comment by selurvedu** [comment]
So not even a snackbar? That's a pity.

**Comment by vfsfitvnm** [comment]
Your idea is totally fine, but the effort is not worth it, unfortunately. Your use case doesn't seem to be popular, i.e. in 20 days no one manifested his interest or whatsoever. Sorry!

**Comment by SebiderSushi** [comment]
I've mentioned this exact same problem on 2022-08-18 in [a comment to issue #143](https://github.com/vfsfitvnm/ViMusic/issues/143#issuecomment-1219513496)

Accidental clicks happen, especially if you have to scroll a lot and literally everywhere you can tap there's a song on screen. Even if most people don't manually build a playing queue - interrupting a song halfway through still sucks if its not intentional.

The ability to choose what happens if i tap on a song goes a long way here and should be a lot easier to implement than other alternatives? At least for my use pattern the issue would be resolved if tapping a song enqueues it instead of playing it.

I almost exclusively work with the playing-queue when i listen to music and if i enqueue a song it is because i want to listen to it, be it now or later. Interrupting a song i am listening to is almost never what i want to do, as is discarding songs i manually added to the playing queue. 80% of the time i interact with a UI element (song, album, playlist) i click enqueue or play next. 5% of the time i actually just click on it and want it to replace the current queue. The remaining 15% is when nothing is playing yet and i pick the first thing to start a new queue with.

Out of all the music players on a mobile device i've used so far only Vanilla Music has complete support for this use pattern. It allows to configure the default action for a single-tap and always allows to play/enqueue a single item or all items on a list. (e.g. i could browse for an album and add one song from it to the queue or play the whole album starting with that song.)
