### ISSUE TITLE
Some features that hopefully people can agree on. :)

### ISSUE THREAD

**Issue by JustNaturalCake** [vfsfitvnm/ViMusic#66]
### Feature description

1. More Rounded Corners, right it now it feels like alot of squares slapped on a paper.
2.  Display the song you're listening to in you're Discord Status.
3.  More app themes like changing the colors from Red, Orange, Yellow, Green, Blue, Purple etc. Its currently only Purple im pretty sure.

### Why do you want this feature?

It will make the overal looks and experience better :)

### Additional information

I don't have any other ideas yet. I love the app so much, keep up the fantastic work 👌

**Comment by JustNaturalCake** [comment]
Idk why it got copied twice

**Comment by JustNaturalCake** [comment]
I'll edit the post if I get up with more simple ideas! :)

**Comment by vfsfitvnm** [comment]
I deleted the other issue.
However, I'm closing this because you didn't follow the feature request template (imprecise title, multiple requests)... more over:

1- You can already have rounded corners (_Settings > Appearance > Thumbnail roundness_);
2- I won't write code for third party apps. Instead, the Android Discord client should do so by reading the media notification and update the user status accordingly;
3- Take a look at #26. Also, theming will improve in the future - don't file a issue unless you have a **very** precise and detailed idea.

**Comment by JustNaturalCake** [comment]
With rounded corners I ment like this
![tempFileForShare_20220701-115554](https://user-images.githubusercontent.com/108516353/176872475-2ce23c8f-f638-43d4-a950-53802a78e95a.jpg)
But yeah thanks for the 1. I didnt notice the roundness in settings :)
