### ISSUE TITLE
Song limit for playlists

### ISSUE THREAD

**Issue by derio-py** [vfsfitvnm/ViMusic#68]
### Steps to reproduce the bug

1. Import any existing playlist from a YouTube Music user with a song count > 100
2. There won't be more than 99 songs in this playlist

### Expected behavior

There should be up to 5000 songs allowed per playlist (YouTube Music set this limit)

### Actual behavior

Not more than 99 songs per playlist

### ViMusic version

0.1.7

### Android version

Android 12

### Additional information

Maybe the reason for this behavior is a limiting data type

**Comment by vfsfitvnm** [comment]
> There should be up to 5000 songs allowed per playlist (YouTube Music set this limit)

Unfortunately this is not true for the method I use to retrieve the songs of a playlist, the limit is 200 (same as https://github.com/snuffyDev/Beatbump/issues/71#issuecomment-1166257417). In fact, Youtube music has a limit of 200 queued songs.

Unfortunately, if you search for that playlist within the app search system, you'll still encounter a cap because I didn't implement a "next page" (continuation) system yet.

_Note to programmers_: the problem is converting a youtube `playlistId` to a youtube music `browseId`.

**Comment by derio-py** [comment]
When will the apk be updated with the newest commitment?

**Comment by vfsfitvnm** [comment]
I don't know, hopefully in a week or two. I want to solve #107 and #108 first.

If you absolutely need it right now, you can:
1. Make a backup of your database (_Settings > Save & Restore_);
2. Install the debug apk here (https://github.com/vfsfitvnm/ViMusic/actions/runs/2686773074) - it will install another application;
3. Open the debug app and restore the database;
4. Find the playlists you need and import them;
5. Make a backup of your database;
6. Open the release app and restore the database.

**Comment by derio-py** [comment]
Aight I'll be checking in again soon. Thank you for the responses, really
shows how you listen to your users!
Have a great day/evening/night!
