### ISSUE TITLE
Always keep favorite songs in cache

### ISSUE THREAD

**Issue by clodi95** [vfsfitvnm/ViMusic#74]
### Feature description

Not really sure how the song cache currently works, but I'm assuming it keeps songs cached in a chronological order, and as soon as the cache is filled up, the oldest songs are removed.

While this is absolutely functional, it would be cool to have a stronger degree of control over the songs kept cached. Namely, it would be great to always keep favorite songs cached no matter the last time you listened to them. Just for reliability reasons.

Also, the space favorite songs take on the phone storage should NOT count toward the max song cache size. This is for 2 reasons:

1) if it did, you could have the issue that a users adds so many songs to their favorites that the favorite songs alone take more space than the set cache size. So the user would add songs to their favorites, thinking they get saved for offline playback, but they don't.

2) it gives more control to the end user. I could set cache size to zero and only have favorite songs being kept cached for offline playback. Or I could have both "recently played" and "favorite" songs being cached.

(Obviously if the song caching system in place already does this, you can close the issue right away)

### Why do you want this feature?

To get the best of both worlds. An automated system that keeps most recently heard songs stored, and a manual system that ensures that songs that matter to you are always available for offline playback.

### Additional information

1) maybe you could add a checkbox in the "Other" Settings to enable and disable this feature

2) to expand on the idea, it would be cool if we could "heart" playlists too, so that one can download an entire playlist with a single tap.

3) probably obvious, but if the user removes a song from their favorites it should not be removed from the device if there's still room in cache. If there isn't, then it should.

**Comment by vfsfitvnm** [comment]
Thanks for filing this detailed feature request.

First of all, I'm not inclined to implement this, it adds **lot** of complexity for little benefits.

> it would be great to always keep favorite songs cached no matter the last time you listened to them

I think this is feasible, but what happens when the cache contains only favorite songs and needs to be evicted? (Keep reading)

> the space favorite songs take on the phone storage should NOT count toward the max song cache size

This isn't a good idea. This would end up using more space than the user wanted to. In your pessimistic (:stuck_out_tongue:) scenario, it could take few extra gigabytes.

> if it did, you could have the issue that a users adds so many songs to their favorites that the favorite songs alone take more space than the set cache size.

Marking a song as favorite is just a quick way to add it to a dedicated playlist. A user that has several gigabytes of favorite songs clearly misinterpreted the purpose. 4GB are 1000 (± 200) songs.

> So the user would add songs to their favorites, thinking they get saved for offline playback, but they don't

This isn't stated anywhere. This is not spotify.

---

That said, the LRU strategy is enough: the song you didn't play for the longest time gets evicted. It just makes sense.
We are dealing with gigabytes, it's just impossible that a song you played the last week or month gets removed from the cache!
Also, if I didn't listen to a song (marked as favorite) for 1 year, then it's not so-favorite, and its reserved space should be given to another song.

It makes no sense to add special rules to retain some songs. What if someone wants another behavior? It will open an identical issue to this one, but "Always keep most played songs in cache", or "Always keep songs that are in a playlist in cache", or "Always keep lady gaga songs in cache". We are back to the start. At this point, what's the point of having a cache, if every song may have a reason to be retained forever?

**Comment by clodi95** [comment]
I understand

**Comment by clodi95** [comment]
(sorry, closed by mistake).

I understand your points, but right now the caching feature is not really useful to me, because I don't have control over what gets download and when.

I usually need to download songs when I'm about to go on a place where I won't have internet for a while, e.g. on an air flight. Right now there is no way to quickly download an album for offline listening. Would I have to open every single track of an album to cache it? Would I have to play the song in its entirety or is just opening it enough? Right now I don't have control over the caching feature, and that makes it unreliable and unusable for me.

I thought that combining the selective download with the favorite feature was a clean a neat way to implement it, no? Because it makes sense that you want your favorite songs to always be available, else why are they your favourites?

**Comment by vfsfitvnm** [comment]
> I don't have control over what gets download and when.

Songs are never downloaded entirely or directly, but they are progressively cached while you listen to them - i.e. if you are about to play **a part** of the song that isn't already cached, then it gets downloaded and played. A chunk is 512kB long. This is necessary to minimize data waste and to not wait ages before playing a new song.

> I usually need to download songs when I'm about to go on a place where I won't have internet for a while, e.g. on an air flight [...] Right now there is no way to quickly download an album for offline listening.

This is true, but it's a different thing if compared to what the issue title says. I'll add a "pre-cache" option to entirely cache a song or a playlist/album, sooner or later.

> A separate, "always available" playlist to which you add the songs you want to download could work too.

This is being worked on (#33).

> This is why I wanted to set cache size to almost zero and only manually cache my favorite songs... That was my reasoning.

This is not what I want as it would imply a huge data waste. It would make sense only if you **never** listen to the same song more than once.
Instead, I could provide some cleanup functions that remove the cache of e.g. every non-favorite song. Such thing would be **way** simpler to implement.

That said, providing a cache system that fits every user needs is utopian. Eventually it will get better, but I have no plans in doing so in a short time. It takes time and there are other features that needs to be addressed first. More over, I can't dedicate this project the same amount of time for the rest of my life (you know, I don't get paid). It will eventually enter in maintenance mode.

**Comment by vfsfitvnm** [comment]
Closing as I don't want to complicate things further - unless someone provides a detailed and precise plan (either via code or technical documentation). 

Related features are tracked in #83 and #95. 

> A separate, "always available" playlist to which you add the songs you want to download could work too.

This is already implemented and will be available within the next release.
