### ISSUE TITLE
Introducing some suggestions

### ISSUE THREAD

**Issue by ghost** [vfsfitvnm/ViMusic#79]
### Feature description

Some suggestion for more convenience

Screenshots and screen recordings are available below

### Why do you want this feature?

For more granular controls and easiness

### Additional information

![IMG_20220704_122727](https://user-images.githubusercontent.com/108591373/177099005-f17e3260-661a-42b4-86e3-4c99b4903b70.jpg)
![IMG_20220704_122521](https://user-images.githubusercontent.com/108591373/177099015-0a990546-2028-4170-a366-fa037b1a1d25.jpg)
![IMG_20220704_114848](https://user-images.githubusercontent.com/108591373/177099021-fb8ac78c-9715-44e7-815e-25442782613c.jpg)
![IMG_20220703_194528](https://user-images.githubusercontent.com/108591373/177099025-727ec98f-27b5-475c-ad22-056abb01473d.jpg)
![IMG_20220703_192826](https://user-images.githubusercontent.com/108591373/177099027-a96a5367-733b-4df7-a5fa-e0228ae3d33f.jpg)

**Comment by mcnano21** [comment]
Hello everyone, I am a french guy totally new on github. I suscribe because I could not find the way to contact people working on ViMusic.
I would like to thank you as the app is just fantastic..
.. as send you one suggestion the make it even better : to reach an Android Auto compatibility. This would be awesome!
Cheers from France,
Lionel

**Comment by vfsfitvnm** [comment]
@mcnano21 Thanks, however you can track that issue here (#47)
