### ISSUE TITLE
download function

### ISSUE THREAD

**Issue by Alliba** [vfsfitvnm/ViMusic#9]
### Feature description

Hi, a great app, it definitely lacks a download function. To listen to the music offline as well.

### Why do you want this feature?

To listen to the music offline as well.

**Comment by vfsfitvnm** [comment]
Hi, the app is already capable of doing offline playback, e.g. you don't need an internet connection to play songs you already listened to.

A simple download feature would just download the given song to the device storage, but then you couldn't play it with ViMusic because it can't play device storage music files (and if it would, it couldn't add those files to playlists).

**Comment by Alliba** [comment]
there is already an offline download function.
